language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer require satooshi/php-coveralls

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
      env: 'COMPOSER_FLAGS="--prefer-stable"'
    - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - travis_retry mkdir -p build/logs

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'